use projetudev;

INSERT INTO marque (lib_marque) VALUES ('ALFA ROMEO');
INSERT INTO marque (lib_marque) VALUES ('ASTON MARTIN');
INSERT INTO marque (lib_marque) VALUES ('AUDI');
INSERT INTO marque (lib_marque) VALUES ('AUSTIN');
INSERT INTO marque (lib_marque) VALUES ('AUTRE');
INSERT INTO marque (lib_marque) VALUES ('BENTLEY');
INSERT INTO marque (lib_marque) VALUES ('BMW');
INSERT INTO marque (lib_marque) VALUES ('CHEVROLET');
INSERT INTO marque (lib_marque) VALUES ('CHRYSLER');
INSERT INTO marque (lib_marque) VALUES ('CITROEN');
INSERT INTO marque (lib_marque) VALUES ('CORVETTE');
INSERT INTO marque (lib_marque) VALUES ('DACIA');
INSERT INTO marque (lib_marque) VALUES ('DAEWOO');
INSERT INTO marque (lib_marque) VALUES ('DS');
INSERT INTO marque (lib_marque) VALUES ('FERRARI');
INSERT INTO marque (lib_marque) VALUES ('FIAT');
INSERT INTO marque (lib_marque) VALUES ('FORD');
INSERT INTO marque (lib_marque) VALUES ('HONDA');
INSERT INTO marque (lib_marque) VALUES ('HYUNDAI');
INSERT INTO marque (lib_marque) VALUES ('INFINITI');
INSERT INTO marque (lib_marque) VALUES ('IVECO');
INSERT INTO marque (lib_marque) VALUES ('JAGUAR');
INSERT INTO marque (lib_marque) VALUES ('JEEP');
INSERT INTO marque (lib_marque) VALUES ('KIA');
INSERT INTO marque (lib_marque) VALUES ('LADA');
INSERT INTO marque (lib_marque) VALUES ('LAMBORGHINI');
INSERT INTO marque (lib_marque) VALUES ('LANCIA');
INSERT INTO marque (lib_marque) VALUES ('LAND ROVER');
INSERT INTO marque (lib_marque) VALUES ('LEXUS');
INSERT INTO marque (lib_marque) VALUES ('LOTUS');
INSERT INTO marque (lib_marque) VALUES ('MASERATI');
INSERT INTO marque (lib_marque) VALUES ('MAZDA');
INSERT INTO marque (lib_marque) VALUES ('MERCEDES');
INSERT INTO marque (lib_marque) VALUES ('MINI');
INSERT INTO marque (lib_marque) VALUES ('MITSUBISHI');
INSERT INTO marque (lib_marque) VALUES ('NISSAN');
INSERT INTO marque (lib_marque) VALUES ('OPEL');
INSERT INTO marque (lib_marque) VALUES ('PEUGEOT');
INSERT INTO marque (lib_marque) VALUES ('PONTIAC');
INSERT INTO marque (lib_marque) VALUES ('PORSCHE');
INSERT INTO marque (lib_marque) VALUES ('RENAULT');
INSERT INTO marque (lib_marque) VALUES ('ROLLS ROYCE');
INSERT INTO marque (lib_marque) VALUES ('ROVER');
INSERT INTO marque (lib_marque) VALUES ('SAAB');
INSERT INTO marque (lib_marque) VALUES ('SEAT');
INSERT INTO marque (lib_marque) VALUES ('SKODA');
INSERT INTO marque (lib_marque) VALUES ('SMART');
INSERT INTO marque (lib_marque) VALUES ('SUBARU');
INSERT INTO marque (lib_marque) VALUES ('SUZUKI');
INSERT INTO marque (lib_marque) VALUES ('TALBOT');
INSERT INTO marque (lib_marque) VALUES ('TOYOTA');
INSERT INTO marque (lib_marque) VALUES ('TRIUMPH');
INSERT INTO marque (lib_marque) VALUES ('VOLKSWAGEN');
INSERT INTO marque (lib_marque) VALUES ('VOLVO');
INSERT INTO marque (lib_marque) VALUES ('APRILIA');
INSERT INTO marque (lib_marque) VALUES ('DUCATI');
INSERT INTO marque (lib_marque) VALUES ('HARLEY-DAVIDSON');
INSERT INTO marque (lib_marque) VALUES ('KAWASAKI');
INSERT INTO marque (lib_marque) VALUES ('KTM');
INSERT INTO marque (lib_marque) VALUES ('PIAGGIO');
INSERT INTO marque (lib_marque) VALUES ('YAMAHA');
INSERT INTO marque (lib_marque) VALUES ('VESPA');
